name: dedicate-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - "python>=3.9,<=3.12" #at least 3.8 for debug
  - numpy
  - matplotlib
  - pathlib
  - pep8
  - pylint
  - seaborn
  - jupyter
  - scipy
  - cython  # for pyamgx
  - "fipy>=3.4"
  #- pytrilinos # no more updated
  - pyamg
  - pip:
      - -e .
